### ISSUE TITLE
time_inbetween failure

### ISSUE THREAD

**Issue by nigelhorne** [jonasbn/perl-test-timer#10]
If a test fails time_inbetween you get "Test did not execute within specified interval"

What you aren't told is whether it executed too quickly or too slowly.

**Comment by jonasbn** [comment]
Hi @nigelhorne,

That sounds like at good idea, let me see what I can do :-)

jonasbn

**Comment by jonasbn** [comment]
@nigelhorne I do not regard it as a failure - but a marvellous enhancement if the method could output that - thanks

**Comment by nigelhorne** [comment]
It if helps, I'm trying to troubleshoot http://www.cpantesters.org/cpan/report/69c755f9-6bf7-1014-ac0b-40aca26eb6e6

It seems to fail on Windows a lot - and I can reproduce it.

**Comment by jonasbn** [comment]
@nigelhorne Oh sounds, but please report as different issue :-)

**Comment by nigelhorne** [comment]
That's not a bug in your software - I think it's a bug in mine, but I'm raising it here because I'm using your software to test/debug mine. It's just an FYI.

**Comment by jonasbn** [comment]
@nigelhorne np, I will try to implement your requirement ASAP

**Comment by jonasbn** [comment]
First shot at implementation available in [branch](https://github.com/jonasbn/perl-test-timer/tree/issue10). I need to work a bit on the docs, but if you have the time, your feedback could prove valuable.

**Comment by nigelhorne** [comment]
At first glance it seems fine, thanks, but I need to test and that'll 
take some doing on a Windoze box :-(

> First shot at implementation available in branch 
> <https://github.com/jonasbn/perl-test-timer/tree/issue10>. I need to 
> work a bit on the docs, but if you have the time, your feedback could 
> prove valuable.
>

**Comment by jonasbn** [comment]
@nigelhorne I will make the official release tomorrow, it is getting late and I want to make sure I remembered everything - I hope that is okay

**Comment by jonasbn** [comment]
Good morning @nigelhorne,

Release 1.00 has just uploaded to PAUSE/CPAN, let me know if you experience any issues. I know your request was not a huge thing. But I actually value the suggestion, I do not know why I dit not see the opportunity myself. Made the release a major release since feedback from the module changed. Again thanks for your suggestion, I hope the release implementation helps you.

**Comment by nigelhorne** [comment]
Sorry it's taken me sometime to test this.  I now get this message:

Test did not execute within specified interval 1 - 6 seconds

Which still doesn't tell me if it took <1 or if it took >6 seconds.

**Comment by jonasbn** [comment]
Don't apologize - I am just glad that you can take the time :-)

I will investigate if I can present the actual calculated execution time. Which sound doable

**Comment by jonasbn** [comment]
Hi @nigelhorne, Please see issue #12 - I have moved your request here.
