### ISSUE TITLE
Display actual calculated execution time in diagnostics

### ISSUE THREAD

**Issue by jonasbn** [jonasbn/perl-test-timer#12]
The implementation introduced in release 1.00, requested by @nigelhorne should be extended after getting some feedback from @nigelhorne.

> Sorry it's taken me sometime to test this. I now get this message:
> Test did not execute within specified interval 1 - 6 seconds
> Which still doesn't tell me if it took <1 or if it took >6 seconds.

**Comment by jonasbn** [comment]
This has been implemented in upcoming release 2.00

**Comment by nigelhorne** [comment]
That looks much better, thanks!

See http://www.cpantesters.org/cpan/report/13bb91f0-4dd7-11e7-9975-d35053e008cf

**Comment by jonasbn** [comment]
Hi @nigelhorne,

Thanks for the feedback I will look into updating the documentation, let me know if you experience any other issues or get ideas for improvements.

jonasbn

**Comment by jonasbn** [comment]
@nigelhorne I had a second look at your example and spotted a bug, please see issue #13 

I have addressed the issue in release 2.01
