### ISSUE TITLE
time_atleast > should be >=

### ISSUE THREAD

**Issue by nigelhorne** [jonasbn/perl-test-timer#15]
See http://www.cpantesters.org/cpan/report/aa2b3bdb-6bf3-1014-8790-aa4ee6406fa7

It comes from this test:

	time_atleast(sub { $response = $ua->get('http://search.cpan.org/'); }, 9, 'should be fully throttled');

Given that it did indeed take at least 9 seconds (it took 9 seconds) that test shouldn't have failed, IMO.

**Comment by jonasbn** [comment]
Hi @nigelhorne 

I am sorry about the long response time, I started cleaning the code a bit after you raised #14, this introduced some instability. I have now stabilised the distribution and will make a release. I have implemented your suggestion.

A release (2.02) should make it to PAUSE/CPAN shortly - have a nice weekend

**Comment by nigelhorne** [comment]
No problem about the delay.  Thanks.  I'll take a look as soon as I can.

**Comment by jonasbn** [comment]
Thanks! and it goes the other way, just whenever you get the time
