### ISSUE TITLE
2.11?

### ISSUE THREAD

**Issue by kloczek** [jonasbn/perl-test-timer#24]
https://metacpan.org/release/Test-Timer says that latest version is 2.11.

There is no tag for that version in git repo.

**Comment by jonasbn** [comment]
Thank you very much for your issue.

The tag 2.11 does exist, where does it not appear?

I have outlined releases 2.10 and 2.11 have now been based on the respective tags.

Take care,

jonabsn

**Comment by jonasbn** [comment]
Closing this issue due to lack of feedback

**Comment by kloczek** [comment]
As tag is now present in git repo I'm OK :)

Thx

**Comment by jonasbn** [comment]
Great, let me know if you run into other issues or questions
